java capflag.Flag -serverName $1 -geomFile capflag/models/flag.tri -position 136.5 101.0 86.5 -lookat 105.0 100.0 90.0 -VUP 0.0 1.0 0.0 -nimbusRadius 5.0 -objName "Right Flag" &

java capflag.Flag -serverName $1 -geomFile capflag/models/flag.tri -position 136.5 101.0 88.5 -lookat 105.0 100.0 90.0 -VUP 0.0 1.0 0.0 -nimbusRadius 5.0 -objName "Wrong Flag" &

java capflag.Flag -serverName $1 -geomFile capflag/models/flag.tri -position 138.5 101.0 86.5 -lookat 105.0 100.0 90.0 -VUP 0.0 1.0 0.0 -nimbusRadius 5.0 -objName "Wrong Flag" &

java capflag.Flag -serverName $1 -geomFile capflag/models/flag.tri -position 138.5 101.0 88.5 -lookat 105.0 100.0 90.0 -VUP 0.0 1.0 0.0 -nimbusRadius 5.0 -objName "Wrong Flag" &

