/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class VCOLLIDE_VCJavaWidget */
/* SYMBOL: "VCOLLIDE_VCJavaWidget/Open()V", Java_VCOLLIDE_VCJavaWidget_Open_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_Open_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void VCOLLIDE_VCJavaWidget_Open(void *);
	(void) VCOLLIDE_VCJavaWidget_Open(_P_[0].p);
	return _P_;
}
/* SYMBOL: "VCOLLIDE_VCJavaWidget/Close()V", Java_VCOLLIDE_VCJavaWidget_Close_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_Close_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void VCOLLIDE_VCJavaWidget_Close(void *);
	(void) VCOLLIDE_VCJavaWidget_Close(_P_[0].p);
	return _P_;
}
/* SYMBOL: "VCOLLIDE_VCJavaWidget/NewObject()I", Java_VCOLLIDE_VCJavaWidget_NewObject_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_NewObject_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long VCOLLIDE_VCJavaWidget_NewObject(void *);
	_P_[0].i = VCOLLIDE_VCJavaWidget_NewObject(_P_[0].p);
	return _P_ + 1;
}
/* SYMBOL: "VCOLLIDE_VCJavaWidget/AddTri(DDDDDDDDD)V", Java_VCOLLIDE_VCJavaWidget_AddTri_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_AddTri_stub(stack_item *_P_,struct execenv *_EE_) {
	Java8 _t1;
	Java8 _t3;
	Java8 _t5;
	Java8 _t7;
	Java8 _t9;
	Java8 _t11;
	Java8 _t13;
	Java8 _t15;
	Java8 _t17;
	extern void VCOLLIDE_VCJavaWidget_AddTri(void *,double,double,double,double,double,double,double,double,double);
	(void) VCOLLIDE_VCJavaWidget_AddTri(_P_[0].p,GET_DOUBLE(_t1, _P_+1),GET_DOUBLE(_t3, _P_+3),GET_DOUBLE(_t5, _P_+5),GET_DOUBLE(_t7, _P_+7),GET_DOUBLE(_t9, _P_+9),GET_DOUBLE(_t11, _P_+11),GET_DOUBLE(_t13, _P_+13),GET_DOUBLE(_t15, _P_+15),GET_DOUBLE(_t17, _P_+17));
	return _P_;
}
/* SYMBOL: "VCOLLIDE_VCJavaWidget/EndObject()V", Java_VCOLLIDE_VCJavaWidget_EndObject_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_EndObject_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void VCOLLIDE_VCJavaWidget_EndObject(void *);
	(void) VCOLLIDE_VCJavaWidget_EndObject(_P_[0].p);
	return _P_;
}
/* SYMBOL: "VCOLLIDE_VCJavaWidget/DeleteObject(I)V", Java_VCOLLIDE_VCJavaWidget_DeleteObject_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_DeleteObject_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void VCOLLIDE_VCJavaWidget_DeleteObject(void *,long);
	(void) VCOLLIDE_VCJavaWidget_DeleteObject(_P_[0].p,((_P_[1].i)));
	return _P_;
}
/* SYMBOL: "VCOLLIDE_VCJavaWidget/ActivateObject(I)V", Java_VCOLLIDE_VCJavaWidget_ActivateObject_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_ActivateObject_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void VCOLLIDE_VCJavaWidget_ActivateObject(void *,long);
	(void) VCOLLIDE_VCJavaWidget_ActivateObject(_P_[0].p,((_P_[1].i)));
	return _P_;
}
/* SYMBOL: "VCOLLIDE_VCJavaWidget/DeactivateObject(I)V", Java_VCOLLIDE_VCJavaWidget_DeactivateObject_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_DeactivateObject_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void VCOLLIDE_VCJavaWidget_DeactivateObject(void *,long);
	(void) VCOLLIDE_VCJavaWidget_DeactivateObject(_P_[0].p,((_P_[1].i)));
	return _P_;
}
/* SYMBOL: "VCOLLIDE_VCJavaWidget/ActivatePair(II)V", Java_VCOLLIDE_VCJavaWidget_ActivatePair_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_ActivatePair_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void VCOLLIDE_VCJavaWidget_ActivatePair(void *,long,long);
	(void) VCOLLIDE_VCJavaWidget_ActivatePair(_P_[0].p,((_P_[1].i)),((_P_[2].i)));
	return _P_;
}
/* SYMBOL: "VCOLLIDE_VCJavaWidget/DeactivatePair(II)V", Java_VCOLLIDE_VCJavaWidget_DeactivatePair_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_DeactivatePair_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void VCOLLIDE_VCJavaWidget_DeactivatePair(void *,long,long);
	(void) VCOLLIDE_VCJavaWidget_DeactivatePair(_P_[0].p,((_P_[1].i)),((_P_[2].i)));
	return _P_;
}
/* SYMBOL: "VCOLLIDE_VCJavaWidget/UpdateTrans(IDDDDDDDDDDDDDDDD)V", Java_VCOLLIDE_VCJavaWidget_UpdateTrans_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_UpdateTrans_stub(stack_item *_P_,struct execenv *_EE_) {
	Java8 _t2;
	Java8 _t4;
	Java8 _t6;
	Java8 _t8;
	Java8 _t10;
	Java8 _t12;
	Java8 _t14;
	Java8 _t16;
	Java8 _t18;
	Java8 _t20;
	Java8 _t22;
	Java8 _t24;
	Java8 _t26;
	Java8 _t28;
	Java8 _t30;
	Java8 _t32;
	extern void VCOLLIDE_VCJavaWidget_UpdateTrans(void *,long,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double);
	(void) VCOLLIDE_VCJavaWidget_UpdateTrans(_P_[0].p,((_P_[1].i)),GET_DOUBLE(_t2, _P_+2),GET_DOUBLE(_t4, _P_+4),GET_DOUBLE(_t6, _P_+6),GET_DOUBLE(_t8, _P_+8),GET_DOUBLE(_t10, _P_+10),GET_DOUBLE(_t12, _P_+12),GET_DOUBLE(_t14, _P_+14),GET_DOUBLE(_t16, _P_+16),GET_DOUBLE(_t18, _P_+18),GET_DOUBLE(_t20, _P_+20),GET_DOUBLE(_t22, _P_+22),GET_DOUBLE(_t24, _P_+24),GET_DOUBLE(_t26, _P_+26),GET_DOUBLE(_t28, _P_+28),GET_DOUBLE(_t30, _P_+30),GET_DOUBLE(_t32, _P_+32));
	return _P_;
}
/* SYMBOL: "VCOLLIDE_VCJavaWidget/Collide()V", Java_VCOLLIDE_VCJavaWidget_Collide_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_Collide_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void VCOLLIDE_VCJavaWidget_Collide(void *);
	(void) VCOLLIDE_VCJavaWidget_Collide(_P_[0].p);
	return _P_;
}
/* SYMBOL: "VCOLLIDE_VCJavaWidget/Report([I)V", Java_VCOLLIDE_VCJavaWidget_Report_stub */
stack_item *Java_VCOLLIDE_VCJavaWidget_Report_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void VCOLLIDE_VCJavaWidget_Report(void *,void *);
	(void) VCOLLIDE_VCJavaWidget_Report(_P_[0].p,((_P_[1].p)));
	return _P_;
}
